In [ ]:
import numpy as np

**Câu 1:** Thay thế tất cả các phần tử trong một mảng có giá trị lớn hơn 30 thành 30 và dưới 10 thành 10.
```
input: [28. 15. 22. 42.  1.  7. 34. 41.  8. 29.]
output: [28. 15. 22. 30. 10. 10. 30. 30. 10. 29.]
```

**Câu 2:** Chuyển một mảng nhiều chiều thành một mảng 1 chiều
```
input: [[0, 1, 2], [3, 4, 5, 6], [7, 8, 9]]
output: [0 1 2 3 4 5 6 7 8 9]
```

**Câu 3:** Tạo one-hot encoding cho một mảng numpy. One-hot encoding nhằm chuyển đổi mỗi giá trị (số nguyên) n thành một vector v mà vị trí thứ n trong vector v mang giá trị 1 và tất cả vị trí khác đều mang giá trị 0.
```
input: [2 1 3 3 1 2]
output: array([[0., 1., 0.],
              [1., 0., 0.],
              [0., 0., 1.],
              [0., 0., 1.],
              [1., 0., 0.],
              [0., 1., 0.]])
```

In [ ]:
import numpy as np
k=[2, 1, 3, 3, 1, 2]
tt=np.zeros((len(k),max(k)))
for i in range(0,len(k)):
  tt[i][k[i]-1]+=1
print(tt)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


**Câu 4:** Sắp xếp các phần tử trong một mảng 1 chiều
```
input: [3 6 4 8]
output: [3 4 6 8]
```

In [ ]:

a= [3, 6, 4, 8 ] 
print(sorted(a))

[3, 4, 6, 8]


,**Câu 5:** Tìm giá trị lớn nhất trong mỗi hàng và mỗi cột của một mảng 2d
```
input
[[5 1 7]
 [3 5 2]
 [6 4 5]]
 
output
Max by column
[6 5 7]
Max by row
[7 5 6]
```

In [ ]:
import numpy as np
a = np.array([[5, 1, 7],
 [3, 5, 2],
 [6, 4 ,5]])
print(a.max(axis = 0))
print(a.max(axis = 1))

[6 5 7]
[7 5 6]


**Câu 6:** Trừ theo dòng, cột mảng 2 chiều arr2d bằng mảng 1 chiều arr1d
```
arr2d
[[3 3 3]
 [4 4 4]
 [5 5 5]]
arr1d
[1 2 1]
output hang
[[2 1 2]
 [3 2 3]
 [4 3 4]]
output cot
[[2 2 2]
 [2 2 2]
 [4 4 4]]
```

In [ ]:
import numpy as np
arr2d = np.array([[3, 3, 3],
 [4, 4, 4],
 [5, 5, 5]]
 )
arr1d = np.array([1, 2, 1])
print(arr2d - arr1d)
print((arr2d.T - arr1d).T)

[[2 1 2]
 [3 2 3]
 [4 3 4]]
[[2 2 2]
 [2 2 2]
 [4 4 4]]


**Câu 7:** Lấy tất cả vị trí nơi các phần tử có giá trị khác nhau
```
input
arr1: [3 4 5 6 7 8]
arr2: [3 3 6 6 7 7]
output
[1, 2, 5]
```

In [ ]:
arr1 = [3, 4, 5, 6, 7, 8]
arr2 = [3, 3, 6, 6, 7, 7]
print([i for i in range(len(arr1)) if arr1[i] not in arr2])

[1, 2, 5]
