In [ ]:
# Import thư viện
import numpy as np

# array
array_ex = np.array([1, 2, 3])
print(array_ex.shape)
print(array_ex[0], array_ex[1])
print('-'*20)

# matrix
matrix_ex = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_ex.shape)
print(matrix_ex)

(3,)
1 2
--------------------
(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
arr_1 = np.array([1, 2, 3])
print(arr_1.shape)
arr_2 = np.array([[1, 2, 3]])
print(arr_2.shape)
arr_3 = np.array([[1], [2], [3]])
print(arr_3.shape)

(3,)
(1, 3)
(3, 1)


In [ ]:
# Một số mảng đặc biệt
a = np.zeros((2, 3))
print(a)
a = np.ones((2, 3))
print(a)
a = np.full((2, 3), 69)
print(a)
a = np.random.random((2, 3))
print(a)
a = np.eye(5)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[69 69 69]
 [69 69 69]]
[[0.7424709  0.7055592  0.99643302]
 [0.5898517  0.82413748 0.44462394]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.zeros((5, 5))
b = a[3:, 3:]
print(a)
print(b)
print('-'*20)

b[0, 0] = 1
print(b)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
--------------------
[[1. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
a = np.array([
               [1, 2, 3],
               [1, 2, 3],
               [1, 2, 3]
])

bool_idx = a > 2
print(bool_idx)
print(a[a > 2])

[[False False  True]
 [False False  True]
 [False False  True]]
[3 3 3]


In [ ]:
a = np.array([
               [1, 2, 3],
               [1, 2, 3],
               [1, 2, 3]
])

b = np.where(a > 2, a, a*10)
print(b)

[[10 20  3]
 [10 20  3]
 [10 20  3]]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

print(A.dot(B))
print(B.dot(A))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [ ]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(A.T)
print('-'*20)
print(A.reshape(2,2,2))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
--------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
A = np.array([1, 2, 3])
print(A + 1)

[2 3 4]


In [ ]:
A = np.asarray([
                [4, 5, 6], 
                [7, 8, 9]
                ])

B = np.asarray([
                [4], 
                [7]
                ])

print(A * B)

[[16 20 24]
 [49 56 63]]
